flows:
  - id: Discovery_Flow_full_catalog
    description: Retail 1.2.5 (Discovery Flow)
    sequence:
      - key: search
        type: search
        unsolicited: false
        pair: on_search
        owner: BAP
        expect: true
        description: BAP sends the search request
        input:
          - name: city_code
            label: Enter the city code
            type: text
            payloadField: $.context.city
          - name: feature_discovery
            label: Features supported
            type: checkbox
            options:
              - code: "007"
                name: "SNP collecting payment"
              - code: "00C"
                name: "Exchange flow"
              - code: "0099"
                name: "Purchase finance"
              - code: "016"
                name: "Customization of input type text"
      - key: on_search
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        label: full catalog
        description: BPP returns the full catalog refresh
  - id: Discovery_Flow_incremental_catalog
    description: "Retail 1.2.5 (Discovery Flow Incremental Catalog)"
    sequence:
      - key: search_inc
        type: search
        unsolicited: false
        pair: null
        owner: BAP
        expect: true
        description: Bap begins search for incremental changes
      - key: on_search_inc
        type: on_search
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: BPP returns the incremental changes
      - key: on_search_inc_disable
        type: on_search
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: BPP returns the incremental changes
      - key: search_inc
        type: search
        unsolicited: false
        pair: null
        owner: BAP
        expect: false
        description: Bap stops search for incremental changes
  - id: Delivery_Flow
    description: Retail 1.2.5 (Delivery)
    sequence: &base_line_flow
      - key: select
        type: select
        unsolicited: false
        pair: on_select
        owner: BAP
        expect: true
        description: BAP select the item
        input:
          - name: fashion_select
            type: ret10_grocery_select
      - key: on_select
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description:
          BPP returns item breakup when item is in stock and offer applied
          (if any)
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
        description: Buyer initiate the product and send the updated fulfillment id
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Respond to init
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
        description: Buyer confirms product
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller Accepts confirmation
      - key: on_status_pending
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order accepted
      - key: on_status_packed
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order packed
      - key: on_status_agent_assigned
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - agent assigned
      - key: on_status_picked
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order picked up
      - key: on_status_out_for_delivery
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order out for delivery
      - key: on_status_order_delivered
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order delivered 
  - id: Out_Of_Stock_Flow
    description: Retail 1.2.5 (Out Of Stock)
    sequence:
      - key: select_out_of_stock
        type: select
        unsolicited: false
        pair: on_select_out_of_stock
        owner: BAP
        expect: true
        description: BAP may add unavailable or out-of-stock items to the cart
      - key: on_select_out_of_stock
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: BPP returns item breakup when item is out of stock
      - key: select
        type: select
        unsolicited: false
        pair: on_select
        owner: BAP
        expect: false
        description: BAP select the item
      - key: on_select
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description:
          BPP returns item breakup when item is in stock and offer applied
          (if any)
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
        description: Buyer initiate the product and send the updated fulfillment id
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Respond to init
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
        description: Buyer confirms product
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller Accepts confirmation
      - key: on_status_pending
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order accepted
      - key: on_status_packed
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order packed
      - key: on_status_agent_assigned
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - agent assigned
      - key: on_status_picked
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order picked up
      - key: on_status_out_for_delivery
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order out for delivery
      - key: on_status_order_delivered
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order delivered
  - id: Buyer_Cancellation_Flow
    description: Retail 1.2.5 (Cancellation)
    sequence:
      - key: select
        type: select
        unsolicited: false
        pair: on_select
        owner: BAP
        expect: true
        description: BAP select the item
        input:
          - name: fashion_select
            type: ret10_grocery_select
      - key: on_select
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description:
          BPP returns item breakup when item is in stock and offer applied
          (if any)
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
        description: Buyer initiate the product and send the updated fulfillment id
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Respond to init
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
        description: Buyer confirms product
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller Accepts confirmation
      - key: cancel
        type: cancel
        unsolicited: false
        pair: on_cancel
        owner: BAP
        expect: false
        description: Buyer side full order cancellation
        input:
          - name: cancellation_reason_id
            label: Select a reason_id
            type: select
            values:
              - "001"
              - "003"
              - "004"
              - "006"
              - "009"
              - "010"
            default: "001"
      - key: on_cancel
        type: on_cancel
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller Accepts cancellation
  - id: Seller_Cancellation_Flow
    description: Retail 1.2.5 (Cancellation)
    sequence:
      - key: select
        type: select
        unsolicited: false
        pair: on_select
        owner: BAP
        expect: true
        description: BAP select the item
        input:
          - name: fashion_select
            type: ret10_grocery_select
      - key: on_select
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description:
          BPP returns item breakup when item is in stock and offer applied
          (if any)
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
        description: Buyer initiate the product and send the updated fulfillment id
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Respond to init
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
        description: Buyer confirms product
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller Accepts confirmation
      - key: on_update_part_cancel
        type: on_update
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Part cancellation request
      - key: update_partial_cancel_settlement
        type: update
        unsolicited: false
        pair: null
        owner: BAP
        expect: false
        description: settlement trail update
      - key: on_status_pending
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order accepted
      - key: on_status_packed
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order packed
      - key: on_status_agent_assigned
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - agent assigned
      - key: on_status_picked
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order picked up
      - key: on_status_out_for_delivery
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order out for delivery
      - key: on_cancel_rto
        type: on_cancel
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Seller side full order cancellation
      - key: on_status_rto_delivereddisposed
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - rto order delivered
  - id: SNP_Collecting_Payment_Flow
    description: Retail 1.2.5 (SNP collecting paymen)
    sequence:
      - key: select
        type: select
        unsolicited: false
        pair: on_select
        owner: BAP
        expect: true
        description: BAP select the item
        input:
          - name: fashion_select
            type: ret10_grocery_select
      - key: on_select
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description:
          BPP returns item breakup when item is in stock and offer applied
          (if any)automation-mock-service/src/config/mock-config/RET14/ELECTRONICS/1.2.5/on_init/on_init
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
        description: Buyer initiate the product and send the updated fulfillment id
      - key: on_init_snp
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Respond to init
      - key: on_init_snp_unsolicited
        type: on_init
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Unsolicited on_init
      - key: confirm_snp
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
        description: Buyer confirms product
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller Accepts confirmation
      - key: on_status_pending
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order accepted
      - key: on_status_packed
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order packed
      - key: on_status_agent_assigned
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - agent assigned
      - key: on_status_picked
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order picked up
      - key: on_status_out_for_delivery
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order out for delivery
      - key: on_status_order_delivered
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order delivered 
  - id: Purchase_Finance_Flow
    description: Retail 1.2.5 (purchase finance)
    sequence: &base_line_flow
      - key: select
        type: select
        unsolicited: false
        pair: on_select
        owner: BAP
        expect: true
        description: BAP select the item
        input:
          - name: fashion_select
            type: ret10_grocery_select
      - key: on_select
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description:
          BPP returns item breakup when item is in stock and offer applied
          (if any)
      - key: init_fin
        type: init
        unsolicited: false
        pair: on_init_fin
        owner: BAP
        expect: false
        description: Buyer initiate the product and send the updated fulfillment id
      - key: on_init_fin
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Respond to init
      - key: confirm_fin
        type: confirm
        unsolicited: false
        pair: on_confirm_fin
        owner: BAP
        expect: false
        description: Buyer confirms product
      - key: on_confirm_fin
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller Accepts confirmation
      - key: on_status_pending_fin
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order accepted
      - key: on_status_packed_fin
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order packed
      - key: on_status_agent_assigned_fin
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - agent assigned
      - key: on_status_picked_fin
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order picked up
      - key: on_status_out_for_delivery_fin
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order out for delivery
      - key: on_status_order_delivered_fin
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order delivered 
  